@startuml
left to right direction
' skinparam linetype ortho
skinparam classAttributeIconSize 0
hide methods

/' Base Classes / Tables '/
class User {
	-Long id
	-String username
	-String email
	-LocalDateTime createdAt
}

class Project {
	-Long id
	-String name
	-String description
	-LocalDateTime createdAt
}

class Task {
	-Long id
	-String title
	-String description
	-TaskState state
	-TaskCategory category
	-Long projectId
	-Long assignedToUserId
	-LocalDateTime createdAt
	-LocalDateTime updatedAt
}
enum TaskState {
	TODO
	IN_PROGRESS
	DONE
}
enum TaskCategory {
	BUG
	FEATURE
	IMPROVEMENT
	RESEARCH
}

class Tag {
	-Long id
	-String name
}

/' N-to-M Mappings '/
/' Do we need this in Java? -> As Table a must '/
class TaskTag <<join table>>{
	-Long taskId
	-Long tagId
}
class ProjectUser <<join table>>{
	-Long projectId
	-Long userId
	-LocalDateTime assignedAt
}


User "0..*" -- "0..*" Project : assigned to
User .. ProjectUser
Project .. ProjectUser
Project "1" -- "0..*" Task : contains
User "0..1" -- "0..*" Task : assigned to
Task "0..*" -- "0..*" Tag : tagged with
Task .. TaskTag
Tag .. TaskTag
Task --> TaskState
Task --> TaskCategory

@enduml