alias c := compile_all
alias d := dump_all

file := "filehandle"

default:
	just --list

build:
	gcc -O2 -S filehandle.c -o out/filehandle.o

view:
	grep -A 50 "use_file" out/filehandle.s | bat --paging=never --style=plain -l asm

disassemble: build
	objdump -d out/filehandle.o > out/filehandle.asm

clean:
	rm -r out && mkdir out

compile_all:
	@just compile {{file}}
	@just compile "{{file}}_unsafe"

dump_all:
	@just dump {{file}}
	@just dump "{{file}}_unsafe"

compile f=file:
	gcc -O2 -c {{f}}.c -o out/{{f}}.o

dump f=file:
	objdump -d out/{{f}}.o > out/{{f}}.asm

