_default:
	@just --list

compile:
	source ../paper/.venv/bin/activate && \
	latexmk -lualatex -output-directory=out -interaction=nonstopmode -shell-escape main.tex
	mv out/main.pdf .

open:
	open main.pdf

clean:
	rm -rf out
