default:
	just --list

run:
	cargo run --release

asm:
	# cargo rustc -- --emit asm
	cargo rustc -- --emit asm -C "llvm-args=-x86-asm-syntax=intel"

asm-release:
	cargo rustc --release -- --emit asm

view:
	bat --style=plain target/release/deps/*.s

fmt:
	cargo +nightly fmt

clippy:
	cargo clippy
