_default:
	@just --list

install:
	brew install inkscape
	uv venv --python 3.11
	uv pip install latexminted==0.5.1

clean:
	rm -r out/
	mkdir out
	touch out/.gitkeep

open:
	open main.pdf

gen_graphs:
	uv run ./scripts/generate_graphs.py
	svgo ./figures/instruction_breakdown.svg
	svgo ./figures/instruction_count.svg

compile:
	source .venv/bin/activate && \
	latexmk -pdf -output-directory=out -shell-escape -interaction=nonstopmode main.tex
	mv out/main.pdf main.pdf

debug:
	source .venv/bin/activate && \
	latexmk -pdf -output-directory=out -shell-escape -verbose -file-line-error -synctex=1 main.tex

